### ISSUE TITLE
The active button style is not overridden for .csh-btn

### ISSUE THREAD

**Issue by stevenmirabito** [ComputerScienceHouse/CSHPublicSite#71]
For a button element with the `.csh-btn` class, the normal and hover states have been overridden to style the button with CSH colors. However, the active state has not, so when the button is clicked the default button colors show:

![](http://i.imgur.com/CXidYxc.gif)

**Comment by brandonhudson** [comment]
I intentionally left this because (my personal opinion) by overriding the :active to match :hover, the user may not know to expect a response from the view. By differentiating between the two, this lets the user know to expect a change on click and shows them the difference between click and hover (hover having no actual actions associated with it). Just my personal opinion though...

**Comment by stevenmirabito** [comment]
Personally, I like the way Bootstrap does it with their buttons, which get a few shades darker on each selector:

![](http://i.imgur.com/epe51YG.gif)

This is achieved with `#B0197E` (40% light) for normal, `#861360` (30% light) for hover/focus, and `#701050` (25% light) for active.

**Comment by brandonhudson** [comment]
Resolved in Pending PR https://github.com/ComputerScienceHouse/CSHPublicSite/pull/59

**Comment by stevenmirabito** [comment]
:+1:

**Comment by stevenmirabito** [comment]
Removed class from the rest of the buttons in https://github.com/stevenmirabito/CSHPublicSite/commit/5b79315e1000ec258955355a0086e8b6df13c7d1 (added to PR #70) in anticipation of PR #59 getting merged.
